def string_detector (s,t):
    locations = []
    i = 0
    while i < len(s):
        i = s.find (t, i)
        if i == -1:
            break
        i = i + 1
        locations.append(i)
        i += 1
    return locations

s = "CTTCTTAATGCGGCGCTCAATGCGGCCTGGATGCGGCGAATGATGCGGCAGCGTATGCGGCATGCGGCAATGCGGCATTCGCATGCGGCTACCCATGCGGCGCAGATGCGGCAGCATATGCGGCTTATGCGGCTATGCGGCATAATGCGGCCATGCGGCATCAATGCGGCTTCGAACCCCGATGCGGCGGTATGCGGCATGAATGCGGCATGCGGCAATGATGCGGCACACACTATGCGGCTCGATGCGGCTAATGCGGCCTATGCGGCTCACTACTATGCGGCGAGCCCTATGCGGCAATGCGGCGATGCGGCGGTATGCGGCAGTATTCATGCGGCCCGTAATGCGGCGATGCGGCGTTAGATATGCGGCTTCCAAATGCGGCATGCGGCATGCGGCATGCGGCTTCCGAATATGCGGCGCATGCGGCTATGCGGCATGCGGCATGCGGCGATGCGGCGTATCACCATGCGGCACATGCGGCAGCCATGGGAATGCGGCTATGCGGCAAGGATGCGGCTATTTGTCATGCGGCATGCGGCATGCGGCATGCGGCGCTCGTCATGCGGCCACGATATGCGGCGCACGTGGTATGCGGCAATGCGGCCGCTAGTAATGCGGCATGCGGCCTATGCGGCATCGCATATGCGGCTGGGATTCATGCGGCTGGCTATGCGGCTTTTCGCTTTGTCCGCATGCGGCTAGTGATGCGGCCATGCGGCGCATGCGGCATGCGGCATGCGGCACATATCTCATGCGGCGCATGCGGCATTATGCGGCGACTGAGCATGCGGCAATGCGGCATGCGGCATGCGGCCATGCGGCGGTACGGATGCGGCCGAAATGCGGCCGATGCGGCTATGCGGC"

t = "ATGCGGCAT"

locations = string_detector (s, t)

print (locations)